# Ansible playbook for deploying the
# ilp-connector, ilp-spsp-client-rest, and ilp-spsp-server
# to the L1P test integration environment

# Note this must be run with the CLI param --extra-vars="docker_username=... docker_password=... docker_email=..."
---
- name: Add hosts
  hosts: localhost
  tags:
    - client
    - server
    - connector
  tasks:

  - add_host:
      name: "ec2-35-166-189-14.us-west-2.compute.amazonaws.com"
      groups: dfsps
      ILP_LEDGER_ADMIN_ACCOUNT: "http://ec2-35-166-189-14.us-west-2.compute.amazonaws.com:8088/ilp/ledger/v1/accounts/admin"
      ILP_LEDGER_ADMIN_USERNAME: admin
      ILP_LEDGER_ADMIN_PASSWORD: admin
      ILP_LEDGER_PREFIX: levelone.dfsp1.
      ILP_SPSP_SERVER_BACKEND: "http://ec2-35-166-189-14.us-west-2.compute.amazonaws.com:8088/spsp/backend"
      ILP_CLIENT_INVOICE_URL_TEMPLATE: "http://ec2-35-166-189-14.us-west-2.compute.amazonaws.com:3043/v1/receivers/invoices/{invoiceId}"
      ILP_CONNECTOR: "levelone.dfsp1.dfsp1-testconnector"
      ILP_CONNECTOR_ACCOUNT: "http://ec2-35-166-189-14.us-west-2.compute.amazonaws.com:8088/ilp/ledger/v1/accounts/dfsp1-testconnector"
      ILP_CONNECTOR_PASSWORD: "1234"
      ILP_CONNECTOR_CENTRAL_LEDGER_ACCOUNT: "http://central-ledger-1139971789.us-west-2.elb.amazonaws.com/accounts/dfsp1"
      ILP_CONNECTOR_CENTRAL_LEDGER_PASSWORD: dfsp1
      ILP_CONNECTOR_PEERS: "levelone.ist.dfsp2"
      CURRENCY: USD
      ILP_CENTRAL_LEDGER_PREFIX: levelone.ist.

  - add_host:
      name: "ec2-35-166-236-69.us-west-2.compute.amazonaws.com"
      groups: dfsps
      ILP_LEDGER_ADMIN_ACCOUNT: "http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:8088/ilp/ledger/v1/accounts/admin"
      ILP_LEDGER_ADMIN_USERNAME: admin
      ILP_LEDGER_ADMIN_PASSWORD: admin
      ILP_LEDGER_PREFIX: levelone.dfsp2.
      ILP_SPSP_SERVER_BACKEND: "http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:8088/spsp/backend"
      ILP_CLIENT_INVOICE_URL_TEMPLATE: "http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:3043/v1/receivers/invoices/{invoiceId}"
      ILP_CONNECTOR_ACCOUNT: "http://ec2-35-166-236-69.us-west-2.compute.amazonaws.com:8088/ilp/ledger/v1/accounts/dfsp2-testconnector"
      ILP_CONNECTOR_PASSWORD: "1234"
      ILP_CONNECTOR_CENTRAL_LEDGER_ACCOUNT: "http://central-ledger-1139971789.us-west-2.elb.amazonaws.com/accounts/dfsp2"
      ILP_CONNECTOR_CENTRAL_LEDGER_PASSWORD: dfsp2
      ILP_CONNECTOR: "levelone.dfsp2.dfsp2-testconnector"
      ILP_CONNECTOR_PEERS: "levelone.ist.dfsp1"
      CURRENCY: USD
      ILP_CENTRAL_LEDGER_PREFIX: levelone.ist.

- name: Configure DFSPs with ILP components
  hosts: dfsps
  remote_user: ec2-user
  tasks:

  - name: Install those deps
    pip:
      name: "docker-py"
    become: true

  - name: Login to Docker repository
    tags:
      - client
      - server
      - connector
    docker_login:
      registry: "modusbox-level1-docker.jfrog.io"
      username: "{{ docker_username }}"
      password: "{{ docker_password }}"
      email: "{{ docker_email }}"

  - name: Start SPSP client REST API
    tags:
      - client
    docker_container:
      name: ilp-spsp-client-rest
      image: "modusbox-level1-docker.jfrog.io/ilp-spsp-client-rest:v4.0.9"
      state: started
      pull: yes
      restart: yes
      ports:
        - "3042:3042"
      log_driver: syslog
      log_options:
        "syslog-address": "tcp://0.0.0.0:514"
        "syslog-facility": "daemon"
        "tag": "ilp-spsp-client-rest"
        "labels": "ilp-spsp-client-rest"
        "env": "ilp-spsp-client-rest"
      env:
        spspclient_port: 3042
        spspclient_prefix: "{{ILP_LEDGER_PREFIX}}"
        spspclient_admin__account: "{{ILP_LEDGER_ADMIN_ACCOUNT}}"
        spspclient_admin__username: "{{ILP_LEDGER_ADMIN_USERNAME}}"
        spspclient_admin__password: "{{ILP_LEDGER_ADMIN_PASSWORD}}"
        spspclient_invoiceUrlTemplate: "{{ILP_CLIENT_INVOICE_URL_TEMPLATE}}"
        # make sure there is a space before the JSON value otherwise ansible will run it as python (?!?!?)
        spspclient_ilp__connectors: >

          ["{{ ILP_CONNECTOR }}"]
        DEBUG: "*"

  - name: Start SPSP server
    tags:
      - server
    docker_container:
      name: ilp-spsp-server
      image: "modusbox-level1-docker.jfrog.io/ilp-spsp-server:v4.1.3"
      state: started
      pull: yes
      restart: yes
      ports:
        - "3043:3043"
      log_driver: syslog
      log_options:
        "syslog-address": "tcp://0.0.0.0:514"
        "syslog-facility": "daemon"
        "tag": "ilp-spsp-server"
        "labels": "ilp-spsp-server"
        "env": "ilp-spsp-server"
      env:
        spsp_port: 3043
        spsp_backend: "{{ILP_SPSP_SERVER_BACKEND}}"
        spsp_prefix: "{{ILP_LEDGER_PREFIX}}"
        spsp_admin__account: "{{ILP_LEDGER_ADMIN_ACCOUNT}}"
        spsp_admin__username: "{{ILP_LEDGER_ADMIN_USERNAME}}"
        spsp_admin__password: "{{ILP_LEDGER_ADMIN_PASSWORD}}"
        DEBUG: "*"

  - name: Start ILP connector
    tags:
      - connector
    docker_container:
      name: ilp-connector
      image: "interledger/js-ilp-connector:v15.1.1"
      state: started
      restart: yes
      pull: yes
      log_driver: syslog
      log_options:
        "syslog-address": "tcp://0.0.0.0:514"
        "syslog-facility": "daemon"
        "tag": "ilp-connector"
        "labels": "ilp-connector"
        "env": "ilp-connector"
      env:
        # make sure there is a space before the JSON value otherwise ansible will run it as python (?!?!?)
        CONNECTOR_LEDGERS: >

          {
            "{{ILP_LEDGER_PREFIX}}": {
              "currency": "{{CURRENCY}}",
              "plugin": "ilp-plugin-bells",
              "options": {
                "account": "{{ILP_CONNECTOR_ACCOUNT}}",
                "password": "{{ILP_CONNECTOR_PASSWORD}}"
              }
            },
            "{{ILP_CENTRAL_LEDGER_PREFIX}}": {
              "currency": "{{CURRENCY}}",
              "plugin": "ilp-plugin-bells",
              "options": {
                "account": "{{ILP_CONNECTOR_CENTRAL_LEDGER_ACCOUNT}}",
                "password": "{{ILP_CONNECTOR_CENTRAL_LEDGER_PASSWORD}}"
              }
            }
          }
        CONNECTOR_PEERS: "{{ILP_CONNECTOR_PEERS}}"
        CONNECTOR_MIN_MESSAGE_WINDOW: 1
        CONNECTOR_MAX_HOLD_TIME: 60
        CONNECTOR_BACKEND: one-to-one
        CONNECTOR_FX_SPREAD: 0
        CONNECTOR_SLIPPAGE: 0
        CONNECTOR_LOG_LEVEL: trace
        DEBUG: "*"
