---
# tasks file for start_service
- name: "Start SG containers -> {{ service_name }}"
  docker_container:
    name: "{{ service_name }}"
    state: started

- name: "Verifing service -> {{ service_name }}"
  uri:
   url: "{{ dfsp[service_name]['validation_url'] }}"
   return_content: yes
  register: result
  until: result.status == 200
  retries: 12
  delay: 5
  when: service_name != 'postgres'