# From the directory above docs:
# (run the copy-images script first)
# dactyl_build -t all -c Docs/ExportDocs/dactyl-config.yml --pdf
#--leave_temp_files
content_path: .
content_static_path: ./images
temporary_files_path: .
template_path: ./Docs/ExportDocs/pdf_templates
template_static_path: ./Docs/ExportDocs/pdf_templates/template_assets
default_template: template-l1p_pdf_content.html
pdf_template: template-l1p_pdf_content.html

filter_paths:
    - ./Docs/ExportDocs/pdf_templates/filters

default_filters:
    - out_of_date
    - link_replacement
    - demote_headers

cover_page:
    display_name: "Index"
    pdf_template: template-l1p_pdf_cover.html
    html: index.html

targets:
    -   name: all
        display_name: Level One Project Full Documentation
        image_re_subs:
            "[./\\w]*/([\\w%.-]+[.](jpg|JPG|png|PNG))": "images/\\1"
        link_subs:
            ./AWS/Infrastructure/machines.md: machines.html
            ./LevelOneClient/scenarios/Send%20Payment.md: SendPayment.html
            ./LevelOneClient: LevelOneClient.html
            ./DFSP/PendingTransactions/README.md: Invoices.html
            ./DFSP/BulkPayment/README.md: BulkPayments.html
            ../../DFSP#default-ports: DFSP.html#default-ports
            ./DFSP: DFSP.html
            ./ILP/ledger-adapter.md: ledger-adapter.html
            ./ILP: ILP.html
            ../CentralDirectory/central_directory_endpoints.md: CentralDirectory.html
            ./CentralDirectory: CentralDirectory.html
            ./CentralLedger: central_ledger.html
            ./CentralRules: central_rules.html
            ./JMeter: IntegrationTests.html
            ./ansible.yml: https://github.com/LevelOneProject/Docs/blob/master/ILP/ansible.yml
            ./ledger-adapter.md: ledger-adapter.html
            ../Ports.md: ports.html
  #      link_re_subs:
  #          "[./\\w]*/([\\w%.-]+[.]md)": "\\1.html"

    -  name: contributor
       display_name: Level One Project Developer Guide

    -  name: stakeholder
       display_name: Level One Project Financial Provider Overview
       image_re_subs:
            "[./\\w]*/([\\w%.-]+[.](jpg|JPG|png|PNG))": "images/\\1"
       link_subs:
            ./AWS/Infrastructure/machines.md: https://github.com/LevelOneProject/Docs/blob/master/AWS/Infrastructure/machines.md         
            ./LevelOneClient/scenarios/Send%20Payment.md: SendPayment.html
            ./LevelOneClient: LevelOneClient.html
            ./DFSP/PendingTransactions/README.md: Invoices.html
            ./DFSP/BulkPayment/README.md: BulkPayments.html
            ../../DFSP#default-ports: DFSP.html#default-ports
            ./DFSP: DFSP.html
            ./ILP/ledger-adapter.md: https://github.com/LevelOneProject/Docs/blob/master/ILP/ledger-adapter.md
            ./ILP: ILP.html
            ../CentralDirectory/central_directory_endpoints.md: https://github.com/LevelOneProject/Docs/blob/master/CentralDirectory/central_directory_endpoints.md
            ./CentralDirectory: https://github.com/LevelOneProject/Docs/blob/master/CentralDirectory
            ./CentralLedger: https://github.com/LevelOneProject/Docs/tree/master/CentralLedger
            ./CentralRules: https://github.com/LevelOneProject/Docs/blob/master/CentralRules            
            ./JMeter: https://github.com/LevelOneProject/Docs/blob/master/JMeter
            ./ansible.yml: https://github.com/LevelOneProject/Docs/blob/master/ILP/ansible.yml
            ./ledger-adapter.md: https://github.com/LevelOneProject/Docs/blob/master/ILP/ledger-adapter.md
            ../Ports.md: https://github.com/LevelOneProject/Docs/blob/master/LevelOneClient/Ports.md


    -  name: regulator
       display_name: Level One Project Compliance Guide

pages:
# /Docs
    -   name: Level One Project Overview
        md: Docs/README.md
        html: overview.html
        category: Overview
        section_header: true
        targets:
            - all
            - contributor
            - stakeholder
            - regulator

    -   name: User Discovery
        html: discovery.html
        category: Overview
        md: Docs/Discovery.md
        targets:
            - all
            - contributor

# Docs/LevelOneClient
# readme.md Ports.md
    -   name: 'Level One Client Overview'
        html: LevelOneClient.html
        category: 'Level One Client'
        md: Docs/LevelOneClient/readme.md
        section_header: true
        targets:
            - all
            - stakeholder

    -   name: 'Clearing Architecture'
        html: ClearingArchitecture.html
        category: 'Level One Client'
        md: 'Docs/ILP/Clearing Architecture.md'
        section_header: true
        targets:
            - all
            - stakeholder

    -   name: 'Level One Client Interledger Components and Flow'
        html: ILP.html
        category: 'Level One Client'
        md: Docs/ILP/README.md
        section_header: true
        targets:
            - all
            - stakeholder


    -   name: 'Level One Client Interop Services'
        html: mule.html
        category: 'Level One Client'
        md: Docs/mule/README.md
        targets:
            - all


    -   name: 'Interledger SPSP Client Interface'
        html: ilp-spsp-client-rest.html
        category: 'Level One Client'
        md:  ilp-spsp-client-rest/README.md
        targets:
            - all


    -   name: 'Interop SPSP Client Proxy'
        html: interop-spsp-clientproxy.html
        category: 'Level One Client'
        md:  interop-spsp-clientproxy/README.md
        targets:
            - all



    -   name: 'Interledger SPSP Server Interface'
        html: ilp-spsp-server.html
        category: 'Level One Client'
        md:  ilp-spsp-server/README.md
        targets:
            - all


    -   name: 'Interop Ledger'
        html: interop-ilp-ledger.html
        category: 'Level One Client'
        md:  interop-ilp-ledger/README.md
        targets:
            - all

    -   name: 'Ledger Adapter'
        html: ledger-adapter.html
        category: 'Level One Client'
        md:  Docs/ILP/ledger-adapter.md
        targets:
            - all
            


    -   name: 'Interop SPSP Backend'
        html: interop-ilp-ledger.html
        category: 'Level One Client'
        md:  interop-spsp-backend-services/README.md
        targets:
            - all



# Docs/LevelOneClient/scenarios
# scenarios 'Send Payment.md'
    -   name: 'Send Payment'
        html: SendPayment.html
        category: Scenarios
        section_header: true # If we make a scenarios intro page move this line to that file
        md: 'Docs/LevelOneClient/scenarios/Send Payment.md'
        targets:
            - all
            - stakeholder

    -   name: 'Pending Transfers'
        html: Invoices.html
        category: Scenarios
        md: Docs/DFSP/PendingTransactions/README.md
        targets:
            - all
            - stakeholder

    -   name: 'Pending Transfers API'
        html: TransferAPI.html
        category: Scenarios
        md: Docs/DFSP/Pending Transactions Api/README.md
        targets:
            - all


    -   name: 'Bulk Payments'
        html: BulkPayments.html
        category: Scenarios
        md: 'Docs/DFSP/BulkPayment/README.md'
        targets:
            - all
            - stakeholder

#Docs/CentralDirectory
# README.md central_directory_endpoints.md
    -   name: 'Central Directory Overview'
        html: CentralDirectory.html
        category: 'Central Directory'
        section_header: true
        md: Docs/CentralDirectory/README.md
        targets:
            - all


    # -   name: 'Central Directory Endpoints'
    #     html: central_directory_endpoints.html
    #     category: 'Central Directory'
    #     md: Docs/CentralDirectory/central_directory_endpoints.md
    #     targets:
    #         - all

    -   name: 'User Retrieval Guide'
        html: UserRetrievalGuide.html
        category: 'Central Directory'
        md: central-directory/UserRetrievalGuide.md
        targets:
            - all

    -   name: 'Central Directory API'
        html: central_directory_API.html
        category: 'Central Directory'
        md: central-directory/API.md
        targets:
            - all

    -   name: 'Directory Gateway'
        html: interop-dfsp-directory.html
        category: 'Central Directory'
        md: interop-dfsp-directory/README.md
        targets:
            - all


#Docs/CentralLedger
# README.md central_ledger_endpoints.md
    -   name: 'Central Ledger Overview'
        html: central_ledger.html
        category: 'Central Ledger'
        section_header: true
        md: Docs/CentralLedger/README.md
        targets:
            - all


    -   name: 'Central Ledger API'
        html: central_ledger_API.html
        category: 'Central Ledger'
        md: central-ledger/API.md
        targets:
            - all


    # -   name: 'Central Ledger Endpoints'
    #     html: central_ledger_endpoints.html
    #     category: 'Central Ledger'
    #     md: Docs/CentralLedger/central_ledger_endpoints.md
    #     targets:
    #         - all
    #         - central
    -   name: 'Execute transfer guide'
        html: execute-transfer-guide.html
        category: 'Central Ledger'
        md: central-ledger/TransferGuide.md
        targets:
            - all


    -   name: 'Central Ledger Setup'
        html: central_ledger_Setup.html
        category: 'Central Ledger'
        md: central-ledger/LevelOneOnboarding.md
        targets:
            - all


#Docs/CentralRules
# README.md central_rules_endpoints.md
    -   name: 'Central Rules Overview'
        html: central_rules.html
        category: 'Central Rules'
        md: Docs/CentralLedger/README.md
        targets:
            - all


    -   name: 'Central Rules Endpoints'
        html: central_rules_endpoints.html
        category: 'Central Rules'
        md: Docs/CentralRules/central_rules_endpoints.md
        targets:
            - all


#Docs/ELK
# ELKSetup.md
    -   name: 'Setup Logging Infrastructure'
        html: elk.html
        category: Infrastructure
        section_header: true # If we add an "Infrastructure" intro, move this to there
        md: Docs/ELK/ELKSetup.md
        targets:
            - all

    -   name: 'Logging Standards'
        html: elk.html
        category: Infrastructure
        md: Docs/mule/logging-guidelines.md
        targets:
            - all

    -   name: 'Forensic Logging Setup'
        html: ForensicSetup.html
        category: Infrastructure
        md: forensic-logging-sidecar/SidecarGuide.md
        targets:
            - all

#Docs/AWS/Infrastructure
# machines.md
    -   name: Machines
        html: machines.html
        category: Infrastructure
        md: Docs/AWS/Infrastructure/machines.md
        targets:
            - all            


    -   name: "Mule's Docker Image"
        html: docker.html
        category: Infrastructure
        md: Docs/mule/docker.md
        targets:
            - all

    -   name: "Configuring High Availability Proxy"
        html: HAProxy.html
        category: Infrastructure
        md: Docs/mule/Configuring HAProxy.md
        targets:
            - all        
  

#Docs/AWS/Infrastructure/PI4-Test-Env
# README.md
    -   name: 'Test Environment'
        html: PI4-Test-Env.html
        category: Infrastructure
        md: Docs/AWS/Infrastructure/PI4-Test-Env/README.md
        targets:
            - all


#Docs/AWS/Infrastructure/PI4-QA-Env
# README.md
    -   name: 'QA Environment'
        html: PI4-QA-Env.html
        category: Infrastructure
        md: Docs/AWS/Infrastructure/PI4-QA-Env/README.md
        targets:
            - all


#Docs/JMeter
    -   name: 'Integration Tests'
        html: IntegrationTests.html
        category: Infrastructure
        md: Docs/JMeter/README.md
        targets:
            - all


    -   name: 'Scenario Tests'
        html: scenarioTests.html
        category: Infrastructure
        md: Docs/JMeter/scenarioTests/readme.md
        targets:
            - all


    -   name: 'Performance Tests'
        html: PerformanceTests.html
        category: Infrastructure
        md: Docs/mule/L1P Performance Test.md 
        targets:
            - all
   

#/Docs/DFSP
#README.md directory.md identity.md notification.md rule.md subscription.md transfer.md account.md development.md BulkPayments.md
    -   name: 'DFSP Overview'
        html: DFSP.html
        section_header: true
        category: DFSP
        md: Docs/DFSP/README.md
        targets:
            - all
            - stakeholder

    -   name: 'Directory'
        html: directory.html
        category: DFSP
        md: Docs/DFSP/directory.md
        targets:
            - all


    -   name: 'Identity'
        html: identity.html
        category: DFSP
        md: Docs/DFSP/identity.md
        targets:
            - all


    -   name: 'Notifications'
        html: notification.html
        category: DFSP
        md: Docs/DFSP/notification.md
        targets:
            - all


    -   name: 'Rules'
        html: rule.html
        category: DFSP
        md: Docs/DFSP/rule.md
        targets:
            - all


    -   name: 'Subscriptions'
        html: subscription.html
        category: DFSP
        md: Docs/DFSP/subscription.md
        targets:
            - all


    -   name: 'Transfer'
        html: transfer.html
        category: DFSP
        md: Docs/DFSP/transfer.md
        targets:
            - all


    -   name: 'Account'
        html: account.html
        category: DFSP
        md: Docs/DFSP/account.md
        targets:
            - all


    -   name: 'ManageAccoutHolders'
        html: ManageAccoutHolders.html
        category: DFSP
        md: Docs/DFSP/ManageAcccoutHolders/ReadMe.md
        targets:
            - all


    -   name: 'Development'
        html: development.html
        category: DFSP
        md: Docs/DFSP/development.md
        targets:
            - all


    -   name: 'Bulk Payments'
        html: BulkPayments.html
        category: DFSP
        md: Docs/DFSP/BulkPayments.md
        targets:
            - all


    -   name: 'USSD'
        html: USSD.html
        category: DFSP
        md: Docs/DFSP/USSD/README.md
        targets:
            - all

# -------------------- Appendix ------------------------
    -   name: 'Terminology'
        html: terminology.html
        section_header: true
        category: Appendix
        md: Docs/terminology.md
        targets:
            - all
            - stakeholder

    -   name: 'Scenario Descriptions'
        html: Scenarios.html
        category: Appendix
        md: Docs/scenarios.md
        targets:
            - all
            - stakeholder

    -   name: 'Tools and Process Decisions'
        html: Decisions.html
        category: Appendix
        md: Docs/decisions.md
        targets:
            - all
            - stakeholder

    -   name: 'Exporting These Documents'
        html: ExportDocs.html
        category: Appendix
        md: Docs/ExportDocs/README.md
        targets:
            - all


# -------------------- Style Checker Rules ------------------------
#word_substitutions_file: plainlanguage_words.yaml
#phrase_substitutions_file: plainlanguage_phrases.yaml
